# nginx proxy address - http://172.17.0.1:8091

name: moodle
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: bitnami/moodle:latest
    pull_policy: always
    container_name: moodle-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - moodle
    ports:
      - "172.17.0.1:8091:8080"
    environment:
      TZ: ${TZ:-America/New_York}
      MOODLE_DATABASE_HOST: moodle-db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: ${DB_CREATE_DATABASE_NAME:-moodle}
      MOODLE_DATABASE_USER: ${DB_USER_NAME:-moodle}
      MOODLE_DATABASE_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      MOODLE_USERNAME: ${APP_ADMIN_USER:-administrator}
      MOODLE_PASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
      MOODLE_EMAIL: ${APP_ADMIN_EMAIL:-admin@example.com}
      MOODLE_SITE_NAME: ${APP_SITE_NAME:-Moodle}
    volumes:
      - ./volumes/data/moodle:/bitnami/moodle
      - ./volumes/data/moodledata:/bitnami/moodledata
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mariadb:latest
    pull_policy: always
    container_name: moodle-db
    hostname: moodle-db
    restart: always
    logging: *default-logging
    networks:
      - moodle
    environment:
      TZ: ${TZ:-America/New_York}
      MARIADB_DATABASE: ${DB_CREATE_DATABASE_NAME:-moodle}
      MARIADB_USER: ${DB_USER_NAME:-moodle}
      MARIADB_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      MARIADB_ROOT_PASSWORD: ${DB_ADMIN_PASS:-changeme_admin_password}
    volumes:
      - ./volumes/data/db/mariadb/moodle:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  moodle:
    name: moodle
    external: false
